version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"
    restart: on-failure
    tty: true
    volumes:
      - ./api/:/app
    env_file:
      - ./.env

networks:
  default:
    name: chatGPT
    external: true